/**
 * generated by Xtext 2.26.0
 */
package iae.post.poST;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Case List</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link iae.post.poST.CaseList#getCaseListElement <em>Case List Element</em>}</li>
 * </ul>
 *
 * @see iae.post.poST.PoSTPackage#getCaseList()
 * @model
 * @generated
 */
public interface CaseList extends EObject
{
  /**
   * Returns the value of the '<em><b>Case List Element</b></em>' containment reference list.
   * The list contents are of type {@link iae.post.poST.SignedInteger}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Case List Element</em>' containment reference list.
   * @see iae.post.poST.PoSTPackage#getCaseList_CaseListElement()
   * @model containment="true"
   * @generated
   */
  EList<SignedInteger> getCaseListElement();

} // CaseList
