/**
 * generated by Xtext 2.26.0
 */
package iae.post.poST;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Error Process Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see iae.post.poST.PoSTPackage#getErrorProcessStatement()
 * @model
 * @generated
 */
public interface ErrorProcessStatement extends ProcessStatements
{
} // ErrorProcessStatement
