/**
 * generated by Xtext 2.26.0
 */
package iae.post.poST;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Exit Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see iae.post.poST.PoSTPackage#getExitStatement()
 * @model
 * @generated
 */
public interface ExitStatement extends Statement
{
} // ExitStatement
