/**
 * generated by Xtext 2.26.0
 */
package iae.post.poST;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Process Statements</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link iae.post.poST.ProcessStatements#getProcess <em>Process</em>}</li>
 * </ul>
 *
 * @see iae.post.poST.PoSTPackage#getProcessStatements()
 * @model
 * @generated
 */
public interface ProcessStatements extends Statement
{
  /**
   * Returns the value of the '<em><b>Process</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Process</em>' reference.
   * @see #setProcess(Variable)
   * @see iae.post.poST.PoSTPackage#getProcessStatements_Process()
   * @model
   * @generated
   */
  Variable getProcess();

  /**
   * Sets the value of the '{@link iae.post.poST.ProcessStatements#getProcess <em>Process</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Process</em>' reference.
   * @see #getProcess()
   * @generated
   */
  void setProcess(Variable value);

} // ProcessStatements
