/**
 * generated by Xtext 2.26.0
 */
package iae.post.poST;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Reset Timer Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see iae.post.poST.PoSTPackage#getResetTimerStatement()
 * @model
 * @generated
 */
public interface ResetTimerStatement extends Statement
{
} // ResetTimerStatement
