/**
 * generated by Xtext 2.26.0
 */
package iae.post.poST;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see iae.post.poST.PoSTPackage#getStatement()
 * @model
 * @generated
 */
public interface Statement extends EObject
{
} // Statement
