/**
 * generated by Xtext 2.26.0
 */
package iae.post.poST;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Statement List</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link iae.post.poST.StatementList#getStatements <em>Statements</em>}</li>
 * </ul>
 *
 * @see iae.post.poST.PoSTPackage#getStatementList()
 * @model
 * @generated
 */
public interface StatementList extends EObject
{
  /**
   * Returns the value of the '<em><b>Statements</b></em>' containment reference list.
   * The list contents are of type {@link iae.post.poST.Statement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Statements</em>' containment reference list.
   * @see iae.post.poST.PoSTPackage#getStatementList_Statements()
   * @model containment="true"
   * @generated
   */
  EList<Statement> getStatements();

} // StatementList
