/**
 * generated by Xtext 2.26.0
 */
package iae.post.poST;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Symbolic Variable</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see iae.post.poST.PoSTPackage#getSymbolicVariable()
 * @model
 * @generated
 */
public interface SymbolicVariable extends Variable
{
} // SymbolicVariable
