/**
 * generated by Xtext 2.26.0
 */
package iae.post.poST;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Template Process Conf Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link iae.post.poST.TemplateProcessConfElement#isActive <em>Active</em>}</li>
 *   <li>{@link iae.post.poST.TemplateProcessConfElement#getProcess <em>Process</em>}</li>
 *   <li>{@link iae.post.poST.TemplateProcessConfElement#getArgs <em>Args</em>}</li>
 * </ul>
 *
 * @see iae.post.poST.PoSTPackage#getTemplateProcessConfElement()
 * @model
 * @generated
 */
public interface TemplateProcessConfElement extends Variable, ProgramConfElement
{
  /**
   * Returns the value of the '<em><b>Active</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Active</em>' attribute.
   * @see #setActive(boolean)
   * @see iae.post.poST.PoSTPackage#getTemplateProcessConfElement_Active()
   * @model
   * @generated
   */
  boolean isActive();

  /**
   * Sets the value of the '{@link iae.post.poST.TemplateProcessConfElement#isActive <em>Active</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Active</em>' attribute.
   * @see #isActive()
   * @generated
   */
  void setActive(boolean value);

  /**
   * Returns the value of the '<em><b>Process</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Process</em>' reference.
   * @see #setProcess(iae.post.poST.Process)
   * @see iae.post.poST.PoSTPackage#getTemplateProcessConfElement_Process()
   * @model
   * @generated
   */
  iae.post.poST.Process getProcess();

  /**
   * Sets the value of the '{@link iae.post.poST.TemplateProcessConfElement#getProcess <em>Process</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Process</em>' reference.
   * @see #getProcess()
   * @generated
   */
  void setProcess(iae.post.poST.Process value);

  /**
   * Returns the value of the '<em><b>Args</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Args</em>' containment reference.
   * @see #setArgs(TemplateProcessElements)
   * @see iae.post.poST.PoSTPackage#getTemplateProcessConfElement_Args()
   * @model containment="true"
   * @generated
   */
  TemplateProcessElements getArgs();

  /**
   * Sets the value of the '{@link iae.post.poST.TemplateProcessConfElement#getArgs <em>Args</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Args</em>' containment reference.
   * @see #getArgs()
   * @generated
   */
  void setArgs(TemplateProcessElements value);

} // TemplateProcessConfElement
