/**
 * generated by Xtext 2.26.0
 */
package iae.post.poST;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Xor Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see iae.post.poST.PoSTPackage#getXorExpression()
 * @model
 * @generated
 */
public interface XorExpression extends Expression
{
} // XorExpression
