/*
 * generated by Xtext 2.26.0
 */
package iae.post.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractPoSTScopeProvider extends DelegatingScopeProvider {
}
